name: CI

on: [push]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        
        - {
            name: "Android",
            os: ubuntu-latest,
            cmake_opts: "-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=armeabi-v7a \
              -DANDROID_PLATFORM=android-19",
            deps_cmdline: "sudo apt update && sudo apt-get install -qq \
              libpulse-dev \
              portaudio19-dev \
              libasound2-dev \
              libjack-dev \
              qtbase5-dev \
              libdbus-1-dev",
            build_type: "Release"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ ! -z "${{matrix.config.deps_cmdline}}" ]]; then
          eval ${{matrix.config.deps_cmdline}}
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} ${{matrix.config.cmake_opts}} .

    - name: Build
      shell: bash
      run: |
        cmake --build build --config ${{matrix.config.build_type}}

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: libopenal
        path: ${{github.workspace}}/build/libopenal.so
